steps:
  # Build and push each service image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west8-docker.pkg.dev/sd-bonus/docker-repo/spring-person:latest', './spring-user']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west8-docker.pkg.dev/sd-bonus/docker-repo/spring-person:latest']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west8-docker.pkg.dev/sd-bonus/docker-repo/spring-device:latest', './spring-device']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west8-docker.pkg.dev/sd-bonus/docker-repo/spring-device:latest']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west8-docker.pkg.dev/sd-bonus/docker-repo/react-app:latest', './react/my-react-app']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west8-docker.pkg.dev/sd-bonus/docker-repo/react-app:latest']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west8-docker.pkg.dev/sd-bonus/docker-repo/monitoring-service:latest', './monitoring']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west8-docker.pkg.dev/sd-bonus/docker-repo/monitoring-service:latest']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west8-docker.pkg.dev/sd-bonus/docker-repo/chat-service:latest', './chat']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west8-docker.pkg.dev/sd-bonus/docker-repo/chat-service:latest']

# Define the images as build artifacts
images:
  - 'europe-west8-docker.pkg.dev/sd-bonus/docker-repo/spring-person:latest'
  - 'europe-west8-docker.pkg.dev/sd-bonus/docker-repo/spring-device:latest'
  - 'europe-west8-docker.pkg.dev/sd-bonus/docker-repo/react-app:latest'
  - 'europe-west8-docker.pkg.dev/sd-bonus/docker-repo/monitoring-service:latest'
  - 'europe-west8-docker.pkg.dev/sd-bonus/docker-repo/chat-service:latest'
